{
 "title": "Openidea - Paimonbank",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Latency - p90",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by (path, method, status, le) (rate(http_request_histogram_bucket[$__rate_interval])))",
     "legendFormat": "{{method}} {{path}} - {{status}}"
    }
   ]
  },
  {
   "title": "Latency - p95",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by (path, method, status, le) (rate(http_request_histogram_bucket[$__rate_interval])))",
     "legendFormat": "{{method}} {{path}} - {{status}}"
    }
   ]
  },
  {
   "title": "Latency - p50",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum by (path, method, status, le) (rate(http_request_histogram_bucket[$__rate_interval])))",
     "legendFormat": "{{method}} {{path}} - {{status}}"
    }
   ]
  },
  {
   "title": "Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(http_request_histogram_bucket{status=\"500\"}[$__rate_interval])) by (path, method, status)",
     "legendFormat": "{{method}} {{path}} - {{status}}"
    }
   ]
  },
  {
   "title": "Throughput - All",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_request_histogram_count[$__rate_interval])) by (path, method, status)",
     "legendFormat": "{{method}} {{path}} - {{status}}"
    }
   ]
  },
  {
   "title": "Number of Goroutines",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "rate(go_goroutines{instance=\"host.docker.internal:8080\", job=\"openidea-paimonbank\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Allocated Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(go_memstats_alloc_bytes{instance=\"host.docker.internal:8080\", job=\"openidea-paimonbank\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}